config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks
  get 'home/index'
  root to: 'home#index' # Not required for API only applications
  get 'home/about'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.where(user: current_user)
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :content, :createdby, :createdat, :completed, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to 'Rails App', root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to 'Home', home_index_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to 'Add Task', new_task_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to 'My Tasks', tasks_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to 'Login', new_user_session_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link"%>
        </li>
      </ul>
      <form class="d-flex">
        <% if user_signed_in? %>
          <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'hidden'%>
          <%= form_for :user, url: destroy_user_session_path, method: :delete do |f| %>
            <%= f.hidden_field :_method, value: :delete %>
            <%= f.submit "Logout" %>
          <% end %>
        <%end%>
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/home/index.html.erb
<% if user_signed_in? %> 
 <div> Welcome <%= current_user.email %> </div> 
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
<% else %>
  <%= button_to "Sign in", new_user_session_path %> 
<% end %>
<h1>Driganka</h1>
<h2> To-Do App</h2>
<h3> CRUD Functionality implemented with Ruby on Rails </h3>

app/views/layouts/_alerts.html.erb
<div class="alert alert-success" role="alert">
  Task was Successfully Created...
</div>

<div class="alert alert-success" role="alert">
  Task Deleted...
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>To Do App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class = 'container'>
      <br/>
      <p class="notice"><%= notice %></p> 
      <p class="alert"><%= alert %></p> 
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :title, class:'form-control', placeholder:"Enter Task Title" %>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.text_area :content, class:'form-control', placeholder:"Enter Task Details" %>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.text_field :createdby, class:'form-control', placeholder:"Enter Your Name", value: current_user.name %>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.datetime_field :createdat, class:'form-control', placeholder:"Enter current Time & Date" %>
  </div>
  <br/>
  <div class="form field-group">
    <%= form.check_box :completed, { class: "class-name", style: "style"}%> Completed
  </div>
  <br/>
  <div class="field form-group">
    <%= form.number_field :user_id, id: :task_user_id, class:"form-control", value: current_user.id  %>
  </div>
  <div class="actions">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Title:</strong>
    <%= task.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= task.content %>
  </p>

  <p>
    <strong>Created by:</strong>
    <%= task.createdby %>
  </p>

  <p>
    <strong>Created at:</strong>
    <%= task.createdat %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= task.completed? %>
  </p>

</div>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/index.html.erb
<h1>Showing all Tasks</h1>

<table class="table table-striped table-bordered table-hover">
    <thead class="table-dark">
      <tr>
        <th>Title</th>
        <th>Task Content</th>
        <th>Created By</th>
        <th>Created At</th>
        <th>Status</th>
        <th> </th>
      </tr>
    </thead>

    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td>
            <%= link_to task.title , task %>
          </td>
          <td><%= task.content %></td>
          <td><%= task.createdby %></td>
          <td><%= task.createdat %></td>
          <td><%= task.completed %></td> </tr>
      <% end %>
    </tbody>
</table>

<%= link_to 'Add New Task', new_task_path, class:'btn btn-secondary' %>

app/views/tasks/new.html.erb
<h2>Add New Task</h2>

<%= render "form", task: @task %>
<br/>
<div>
  <%= link_to "Back", tasks_path, class:"btn btn-secondary btn-dark" %>
</div>

app/views/tasks/show.html.erb
<div class="jumbotron">
  <h3 class="display-7"><%= render @task %></h3>
  <hr class="my-4">
  <%= link_to 'Edit', edit_task_path, class:'btn btn-secondary' %>
  <%= link_to 'Back', tasks_path, class:'btn btn-secondary' %>
  <div class="delete">
    <!-- Below, link_to DOES NOT WORK -->
    <%= button_to 'Delete', @task, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger btn-lg' %>
  </div>
</div>